

export const darkTheme = {
  mode:"dark",
  PRIMARY_BACKGROUND_COLOR:"#1E272E",
  PRIMARY_TEXT_COLOR:"#fff",
  SECONDARY_TEXT_COLOR:"#fff",
  PRIMARY_BUTTON_COLOR:"#152642",
  SECONDARY_BUTTON_COLOR:"#506680"
}

export const lightTheme = {
  mode:"light",
  PRIMARY_BACKGROUND_COLOR:"#F1F2F6",
  PRIMARY_TEXT_COLOR:"#2F3542",
  SECONDARY_TEXT_COLOR:"#fff",
  PRIMARY_BUTTON_COLOR:"#2F3542",
  SECONDARY_BUTTON_COLOR:"#2F3542"
}